# Generated by Django 3.0.7 on 2020-06-11 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sbadmin.Position', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='registration_code',
            field=models.IntegerField(verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Cargo'),
        ),
    ]
