# Generated by Django 3.0.7 on 2020-06-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbadmin', '0004_auto_20200611_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='registration_code',
            field=models.IntegerField(unique=True, verbose_name='Matrícula'),
        ),
    ]
