# Generated by Django 3.0.7 on 2020-10-23 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbadmin', '0005_auto_20200623_1801'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry_Log',
        ),
    ]
