# Generated by Django 3.0.7 on 2020-10-23 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbadmin', '0006_delete_entry_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sbadmin.Employee')),
            ],
        ),
    ]
