# Generated by Django 3.0.7 on 2020-10-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbadmin', '0008_auto_20201023_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry_log',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Entrada'), (2, 'Saída')], default=1),
        ),
    ]
