# Generated by Django 3.0.7 on 2020-10-23 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbadmin', '0009_entry_log_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry_log',
            old_name='tipo',
            new_name='type',
        ),
    ]
