# Generated by Django 3.0.7 on 2020-10-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbadmin', '0010_auto_20201023_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='digital',
            field=models.BooleanField(default=False),
        ),
    ]
