# Generated by Django 3.0.7 on 2020-10-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbadmin', '0012_employee_digitalhash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='digitalHash',
            field=models.TextField(null=True),
        ),
    ]
