# Generated by Django 3.0.7 on 2020-10-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbadmin', '0013_auto_20201029_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='digitalHash',
            field=models.TextField(blank=True, null=True),
        ),
    ]
