# Generated by Django 3.0.7 on 2020-10-30 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbadmin', '0014_auto_20201029_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='digital',
        ),
    ]
