# Generated by Django 3.0.7 on 2020-10-30 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbadmin', '0015_remove_employee_digital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='digitalHash',
            field=models.TextField(blank=True, null=True, unique=True, verbose_name='Hash da Digital'),
        ),
        migrations.AlterField(
            model_name='position',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sbadmin.Area', verbose_name='Área'),
        ),
    ]
